version: '3.1'
services:
  redis-server:
    image: redis
    container_name: redis-server
    hostname: redis-server
    ports:
      - '6379:6379'

  api-server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: api-server
    ports:
      - '3000:3000'
    depends_on:
      - redis-server
